### ISSUE TITLE
Failure establishing SSH session

### ISSUE THREAD

**Issue by jowparks** [dylankenneally/react-native-ssh-sftp#11]
FWIW I solved the issue here:
https://github.com/dylankenneally/react-native-ssh-sftp-example/issues/2

I solved it by referencing this post:
https://stackoverflow.com/a/77379429/8041091

1. I forked this repo
2. updated the `NMSSH` to the verison here:
https://github.com/speam/NMSSH
3. Added that git version of `NMSSH` to my pod file
4. Fixed a compiler error (forget what it was)
5. installed my version in my react-native project
6. Connected successfully

**Comment by dylankenneally** [comment]
Thank you @jowparks for reporting this and providing a a fix. I've made the changes you've suggested - works great.
