### ISSUE TITLE
Problem while trying to connect to SFTP server

### ISSUE THREAD

**Issue by aymanMFD** [dylankenneally/react-native-ssh-sftp#16]
Hi! 
I am new to React and its libraries and I can't seem to figure out how to connect to an SFTP server. Its true that in the README file there are the steps and all, but since I am a beginner I cant seem to understand, sorry for the inconvenience.
Hope you can help

**Comment by dylankenneally** [comment]
Hey @aymanMFD 

More than happy to try help out. As you're asking about a "how do I do ... ?" topic, I've opened discussions on this repo and moved your query there. Checkout https://github.com/dylankenneally/react-native-ssh-sftp/discussions/17 to continue the conversation.
