### ISSUE TITLE
[BUG] error building IOS-simulator / linking error

### ISSUE THREAD

**Issue by modeling** [dylankenneally/react-native-ssh-sftp#20]
Installing this on a clean install of react-native 0.74.1 for iOS on a M1 mac with latest version of Xcode (15.4) and Sonoma (14.5) returns the following error when attempting to build and run it on the simulator. 

Building for 'iOS-simulator', but linking in object file (/Users/me/Projects/synccomputer/ios/Pods/NMSSH/NMSSH-iOS/Libraries/lib/libcrypto.a[arm64][2](aes_cbc.o)) built for 'iOS'

Thank you.

**Comment by dylankenneally** [comment]
Thanks for raising this @modeling; it's been a known issue for me for a while - I just haven't found the time to resolve it yet.

The NMSSH obj files we're using are not present for the simulator at this time. It is possible to build them for both real devices and the simulator, if you'd like to give that a try then you might find the comments on [this issue](https://github.com/NMSSH/NMSSH/issues/253) helpful. Note though, that we are using a [fork of NMSSH](https://github.com/speam/NMSSH) to give us the needed version of libssh2. If you do go down this path, I'd welcome a PR to help others facing the same issue.

Alternatively, you can connect your real iPhone to your mac and run your project on it.

**Comment by modeling** [comment]
It's good to know this works fine if we just use it with an actual device. May I suggest adding a quick note to the installations instructions that this component must be run on an actual device and not in the simulator. Thank you for building such a useful component.

**Comment by dylankenneally** [comment]
Good call on the doco @modeling - done.
