### ISSUE TITLE
[Enhancement request] update jsch to support  ed25519 Key

### ISSUE THREAD

**Issue by raghulkrishna** [dylankenneally/react-native-ssh-sftp#22]
Currently jsch package doesnt support ed25519 Key update the jsch to support them  for android
https://github.com/mwiede/jsch/tree/master

In ios only old rsa keys are supported not new rsa or ed25519 keys are supported

**Comment by dylankenneally** [comment]
Thanks for creating this enhancement request @raghulkrishna.

I'll need to investigate this a little further before replacing the JSch package, in particular I'll need to look at the impact of [this comment](https://github.com/mwiede/jsch/tree/master?tab=readme-ov-file#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server) and [this comment](https://github.com/mwiede/jsch/tree/master?tab=readme-ov-file#is-this-fork-100-compatible-with-original-jsch-because-the-connection-to-my-server-does-not-work-any-more) from your suggested replacement package.

This is being used commercially for an app that configures IoT hardware, so let me look in to compatibility before proceeding.

**Comment by csaben** [comment]
@dylankenneally it's a drop in replacement in your `build.gradle`.
`mwiede` made a blog post about it [here](https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa/).

originally, I was hitting `Algorithm negotiation fail` everywhere. After replacing 
```diff
- api 'com.jcraft:jsch:0.1.55'
+ api 'com.github.mwiede:jsch:0.1.58'
```
in my `node_modules` in your app's build.gradle, everything works without adjusting any imports.

Thanks for maintaining this repo, it's been great so far!

**Comment by raghulkrishna** [comment]
@csaben were you able to use ed25519 keys

**Comment by csaben** [comment]
> @csaben were you able to use ed25519 keys

just generated one with `ssh-keygen -t ed25519` and tried but get an invalid key error again. So, unless I'm messing up somewhere else, no.

**Comment by raghulkrishna** [comment]
> > @csaben were you able to use ed25519 keys
> 
> just generated one with `ssh-keygen -t ed25519` and tried but get an invalid key error again. So, unless I'm messing up somewhere else, no.

is this for ios or android?

**Comment by raghulkrishna** [comment]
@dylankenneally for ios here you have the latest libssh module in NMSSH https://github.com/aanah0/NMSSH

**Comment by csaben** [comment]
> > > @csaben were you able to use ed25519 keys
> > 
> > just generated one with `ssh-keygen -t ed25519` and tried but get an invalid key error again. So, unless I'm messing up somewhere else, no.
> 
> is this for ios or android?

android

**Comment by dylankenneally** [comment]
Thanks for your input @csaben and @raghulkrishna, I've updated both NMSSH and jsch based on your suggestions in release [1.5.18](https://github.com/dylankenneally/react-native-ssh-sftp/releases/tag/v1.5.18) (available on npm).

I'll leave this issue open for a couple of days to see if you have any feedback on this version.

**Comment by raghulkrishna** [comment]
@dylankenneally take a look at this https://github.com/raghulkrishna/react-native-ssh-sftp/blob/master/android/build.gradle 

we need to ad a dependency for android     implementation 'org.bouncycastle:bcprov-jdk15on:1.70' to make ed25519 kys based auth

I am also testing key generation and key information https://github.com/raghulkrishna/react-native-ssh-sftp/blob/master/src/sshclient.ts 
This works only for android (i dont know how to update ios)

**Comment by dylankenneally** [comment]
@raghulkrishna thank you that.

I'd be more than happy to review & accept PR's for the changes you're suggesting if you would like to collaborate. I'd suggest sending seperate PR's if you're happy to:

1. to get ed25519 keys based auth working
2. for key generation and key information

> This works only for android (i dont know how to update ios)

Re the above 👆, we could take your second PR for key generation to a feature branch, and I (or others) could take a look at the iOS part, or I could put some scaffolding in place for iOS as a stop gap.

Let me know your thoughts.

**Comment by raghulkrishna** [comment]
@dylankenneally  i updated the changes here https://github.com/dylankenneally/react-native-ssh-sftp/pull/25/files it would be nice if you could implemement similar to ios
